name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up GDAL from PPA (latest version)
        run: |
          sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Print GDAL version
        run: gdalinfo --version

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
